[phases.setup]
nixPkgs = ["python39", "python39Packages.pip", "python39Packages.setuptools", "bash"]

[phases.install]
cmds = ["chmod +x build.sh", "./build.sh"]

[phases.build]
cmds = ["echo 'Build phase complete'"]

[start]
cmd = "cd llm_stuff && python search_api.py"

[variables]
NIXPACKS_PYTHON_VERSION = "3.9"