[phases.setup]
nixPkgs = [
  "python39",
  "python39Packages.pip",
  "python39Packages.setuptools",
  "gcc",
  "gfortran",
  "pkg-config",
  "bash"
]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip setuptools wheel",
  "python -m pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Build phase complete'"]

[start]
cmd = "cd llm_stuff && python search_api.py"

[variables]
NIXPACKS_PYTHON_VERSION = "3.9"